services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soundle
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
