import { Injectable } from '@angular/core';
import {Observable, of} from "rxjs";

@Injectable({
  providedIn: 'root'
})
export class AutocompleteService {

  private animeNames: string[] = [
    "Shingeki no Kyojin",
    "Death Note",
    "Fullmetal Alchemist: Brotherhood",
    "One Punch Man",
    "Sword Art Online",
    "Kimetsu no Yaiba",
    "Boku no Hero Academia",
    "Naruto",
    "Hunter x Hunter (2011)",
    "Tokyo Ghoul",
    "Kimi no Na wa.",
    "Shingeki no Kyojin Season 2",
    "Steins;Gate",
    "Jujutsu Kaisen",
    "Boku no Hero Academia 2nd Season",
    "Naruto: Shippuuden",
    "No Game No Life",
    "Shingeki no Kyojin Season 3",
    "One Piece",
    "Koe no Katachi",
    "Shingeki no Kyojin Season 3 Part 2",
    "Code Geass: Hangyaku no Lelouch",
    "Shigatsu wa Kimi no Uso",
    "Toradora!",
    "Re:Zero kara Hajimeru Isekai Seikatsu",
    "Boku no Hero Academia 3rd Season",
    "Noragami",
    "Boku dake ga Inai Machi",
    "Akame ga Kill!",
    "Angel Beats!",
    "Mob Psycho 100",
    "Nanatsu no Taizai",
    "Ansatsu Kyoushitsu",
    "Mirai Nikki (TV)",
    "Shingeki no Kyojin: The Final Season",
    "Sword Art Online II",
    "Haikyuu!!",
    "Yakusoku no Neverland",
    "Bleach",
    "Kono Subarashii Sekai ni Shukufuku wo!",
    "Ao no Exorcist",
    "Kiseijuu: Sei no Kakuritsu",
    "Cowboy Bebop",
    "Sen to Chihiro no Kamikakushi",
    "Shinseiki Evangelion",
    "Violet Evergarden",
    "Code Geass: Hangyaku no Lelouch R2",
    "Tokyo Ghoul √A",
    "Death Parade",
    "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
    "Fairy Tail",
    "Dr. Stone",
    "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
    "Boku no Hero Academia 4th Season",
    "Kill la Kill",
    "One Punch Man 2nd Season",
    "Another",
    "Black Clover",
    "JoJo no Kimyou na Bouken (TV)",
    "Darling in the FranXX",
    "Shokugeki no Souma",
    "Psycho-Pass",
    "Soul Eater",
    "Tengen Toppa Gurren Lagann",
    "Charlotte",
    "Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.",
    "Overlord",
    "Tate no Yuusha no Nariagari",
    "Hataraku Maou-sama!",
    "Spy x Family",
    "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
    "Mob Psycho 100 II",
    "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
    "Vinland Saga",
    "Chainsaw Man",
    "Kono Subarashii Sekai ni Shukufuku wo! 2",
    "Elfen Lied",
    "Highschool of the Dead",
    "Fate/Zero",
    "Kakegurui",
    "Fullmetal Alchemist",
    "Noragami Aragoto",
    "Tensei shitara Slime Datta Ken",
    "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
    "Ansatsu Kyoushitsu 2nd Season",
    "Haikyuu!! Second Season",
    "High School DxD",
    "Kimetsu no Yaiba: Yuukaku-hen",
    "Clannad",
    "Durarara!!",
    "Bakemonogatari",
    "Bungou Stray Dogs",
    "Horimiya",
    "Made in Abyss",
    "Hyouka",
    "Chuunibyou demo Koi ga Shitai!",
    "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
    "Howl no Ugoku Shiro",
    "Enen no Shouboutai",
    "Owari no Seraph",
    "Mushoku Tensei: Isekai Ittara Honki Dasu",
    "Shingeki no Kyojin: The Final Season Part 2",
    "Mahou Shoujo Madoka★Magica",
    "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
    "Mononoke Hime",
    "Tokyo Revengers",
    "Kaichou wa Maid-sama!",
    "Sakura-sou no Pet na Kanojo",
    "Samurai Champloo",
    "Deadman Wonderland",
    "Kobayashi-san Chi no Maid Dragon",
    "Dragon Ball Z",
    "Dororo",
    "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders",
    "Guilty Crown",
    "Kuroko no Basket",
    "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
    "Clannad: After Story",
    "Tokyo Ghoul:re",
    "Kuroshitsuji",
    "Boku no Hero Academia 5th Season",
    "Nisekoi",
    "Zankyou no Terror",
    "Kyoukai no Kanata",
    "Devilman: Crybaby",
    "Shokugeki no Souma: Ni no Sara",
    "Goblin Slayer",
    "Nanatsu no Taizai: Imashime no Fukkatsu",
    "Ouran Koukou Host Club",
    "JoJo no Kimyou na Bouken Part 4: Diamond wa Kudakenai",
    "Monster",
    "Log Horizon",
    "Fate/Zero 2nd Season",
    "JoJo no Kimyou na Bouken Part 3: Stardust Crusaders 2nd Season",
    "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season",
    "Saiki Kusuo no Ψ-nan",
    "Tonari no Kaibutsu-kun",
    "Fate/stay night: Unlimited Blade Works",
    "Mahouka Koukou no Rettousei",
    "Gintama",
    "Tonari no Totoro",
    "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku",
    "Sono Bisque Doll wa Koi wo Suru",
    "K-On!",
    "Sword Art Online: Alicization",
    "Magi: The Labyrinth of Magic",
    "Golden Time",
    "Dragon Ball",
    "Dr. Stone: Stone Wars",
    "ReLIFE",
    "Date A Live",
    "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
    "Overlord II",
    "Prison School",
    "Black Lagoon",
    "Tenki no Ko",
    "Fairy Tail (2014)",
    "Wotaku ni Koi wa Muzukashii",
    "Kanojo, Okarishimasu",
    "Shokugeki no Souma: San no Sara",
    "Kimi no Suizou wo Tabetai",
    "Tensei shitara Slime Datta Ken 2nd Season",
    "Rakudai Kishi no Cavalry",
    "Kimi ni Todoke",
    "5-toubun no Hanayome",
    "Darker than Black: Kuro no Keiyakusha",
    "Jujutsu Kaisen 0 Movie",
    "Plastic Memories",
    "Byousoku 5 Centimeter",
    "Fate/stay night",
    "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation",
    "Haikyuu!! To the Top",
    "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
    "Hellsing Ultimate",
    "Mahoutsukai no Yome",
    "Ao Haru Ride",
    "Gekkan Shoujo Nozaki-kun",
    "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    "Kami no Tou",
    "Yakusoku no Neverland 2nd Season",
    "Jujutsu Kaisen 2nd Season",
    "Black Bullet",
    "Youjo Senki",
    "Suzumiya Haruhi no Yuuutsu",
    "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
    "Spy x Family Part 2",
    "High School DxD New",
    "The God of High School",
    "Overlord III",
    "Baccano!",
    "Nichijou",
    "Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2",
    "Yuri!!! on Ice",
    "Komi-san wa, Comyushou desu.",
    "Tokyo Ghoul:re 2nd Season",
    "Masamune-kun no Revenge",
    "Kekkai Sensen",
    "Steins;Gate 0",
    "No Game No Life: Zero",
    "Fumetsu no Anata e",
    "2024-05-07T12:37:33.455-03:00Kotonoha no Niwa",
    "Boruto: Naruto Next Generations",
    "Banana Fish",
    "Btooom!",
    "Bungou Stray Dogs 2nd Season",
    "Kuroko no Basket 2nd Season",
    "Beastars",
    "Akatsuki no Yona",
    "Fate/stay night: Unlimited Blade Works 2nd Season",
    "Akira",
    "Magi: The Kingdom of Magic",
    "Trinity Seven",
    "Fruits Basket 1st Season",
    "Kokoro Connect",
    "Mushishi",
    "Dragon Ball Super",
    "Great Teacher Onizuka",
    "Orange",
    "Danshi Koukousei no Nichijou",
    "FLCL",
    "Hotarubi no Mori e",
    "Ookami to Koushinryou",
    "Zero no Tsukaima",
    "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka II",
    "Toaru Majutsu no Index",
    "Kimetsu no Yaiba: Katanakaji no Sato-hen",
    "Haikyuu!! To the Top Part 2",
    "Koutetsujou no Kabaneri",
    "Ookami Kodomo no Ame to Yuki",
    "Boku wa Tomodachi ga Sukunai",
    "Gate: Jieitai Kanochi nite, Kaku Tatakaeri",
    "Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai",
    "Higurashi no Naku Koro ni",
    "High School DxD BorN",
    "Free!",
    "Ijiranaide, Nagatoro-san",
    "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou",
    "InuYasha",
    "Toki wo Kakeru Shoujo",
    "Owari no Seraph: Nagoya Kessen-hen",
    "Yamada-kun to 7-nin no Majo",
    "Oshi no Ko",
    "Kono Subarashii Sekai ni Shukufuku wo! Movie: Kurenai Densetsu",
    "Grand Blue",
    "Shinsekai yori",
    "Serial Experiments Lain",
    "Kakegurui××",
    "86",
    "Sakamoto desu ga?",
    "Enen no Shouboutai: Ni no Shou",
    "Ao no Exorcist: Kyoto Fujouou-hen",
    "Trigun",
    "Kuroko no Basket 3rd Season",
    "Sword Art Online: Alicization - War of Underworld",
    "Tensei shitara Slime Datta Ken 2nd Season Part 2",
    "K",
    "Tate no Yuusha no Nariagari Season 2",
    "Wonder Egg Priority",
    "Domestic na Kanojo",
    "Kimetsu no Yaiba: Mugen Ressha-hen",
    "Monster Musume no Iru Nichijou",
    "Boku no Hero Academia the Movie 1: Futari no Hero",
    "Cyberpunk: Edgerunners",
    "NHK ni Youkoso!",
    "Kiznaiver",
    "Tonikaku Kawaii",
    "Chuunibyou demo Koi ga Shitai! Ren",
    "Hai to Gensou no Grimgar",
    "Nisemonogatari",
    "Rokudenashi Majutsu Koushi to Akashic Records",
    "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan",
    "Tsurezure Children",
    "Sword Art Online Movie: Ordinal Scale",
    "Nanatsu no Taizai: Kamigami no Gekirin",
    "Hellsing",
    "Isekai Maou to Shoukan Shoujo no Dorei Majutsu",
    "91 Days",
    "Sousou no Frieren",
    "Shokugeki no Souma: San no Sara - Tootsuki Ressha-hen",
    "Eromanga-sensei",
    "Nanatsu no Taizai: Seisen no Shirushi",
    "Accel World",
    "5-toubun no Hanayome ∬",
    "Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai",
    "Perfect Blue",
    "Arifureta Shokugyou de Sekai Saikyou",
    "Nisekoi:",
    "K-On!!",
    "D.Gray-man",
    "Himouto! Umaru-chan",
    "Yuu☆Yuu☆Hakusho",
    "Blood Lad",
    "Rosario to Vampire",
    "Kuzu no Honkai",
    "Ore no Imouto ga Konnani Kawaii Wake ga Nai",
    "3-gatsu no Lion",
    "Shinmai Maou no Testament",
    "Akagami no Shirayuki-hime",
    "Hotaru no Haka",
    "Ore Monogatari!!",
    "Mob Psycho 100 III",
    "Blue Lock",
    "Claymore",
    "Jigokuraku",
    "Satsuriku no Tenshi",
    "Monogatari Series: Second Season",
    "Nana",
    "School Days",
    "Great Pretender",
    "Barakamon",
    "Saenai Heroine no Sodatekata",
    "Gakusen Toshi Asterisk",
    "Blend S",
    "Kenpuu Denki Berserk",
    "Amagi Brilliant Park",
    "Kamisama Hajimemashita",
    "Psycho-Pass 2",
    "Suki tte Ii na yo.",
    "Watashi ga Motenai no wa Dou Kangaetemo Omaera ga Warui!",
    "Gamers!",
    "Lucky☆Star",
    "Ergo Proxy",
    "Hataraku Saibou",
    "Inuyashiki",
    "Little Witch Academia (TV)",
    "Ousama Ranking",
    "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    "Saiki Kusuo no Ψ-nan 2",
    "Boku no Hero Academia 6th Season",
    "Kage no Jitsuryokusha ni Naritakute!",
    "To LOVE-Ru",
    "Strike the Blood",
    "Date A Live II",
    "IS: Infinite Stratos",
    "Koukaku Kidoutai",
    "Baka to Test to Shoukanjuu",
    "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 2nd Season",
    "Rokka no Yuusha",
    "Bungou Stray Dogs 3rd Season",
    "Pokemon",
    "Dragon Ball GT",
    "Ore dake Level Up na Ken",
    "Gintama°",
    "Kami nomi zo Shiru Sekai",
    "Kore wa Zombie desu ka?",
    "Sword Art Online Alternative: Gun Gale Online",
    "Shinchou Yuusha: Kono Yuusha ga Ore Tueee Kuse ni Shinchou Sugiru",
    "Bakuman.",
    "Sankarea",
    "Shokugeki no Souma: Shin no Sara",
    "Sword Art Online: Alicization - War of Underworld 2nd Season",
    "Grisaia no Kajitsu",
    "Log Horizon 2nd Season",
    "Violet Evergarden Movie",
    "Suzumiya Haruhi no Shoushitsu",
    "The Last: Naruto the Movie",
    "Toaru Kagaku no Railgun",
    "Hige wo Soru. Soshite Joshikousei wo Hirou.",
    "Vinland Saga Season 2",
    "Vampire Knight",
    "Nagi no Asu kara",
    "Shiki",
    "Zetsuen no Tempest",
    "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka III",
    "Beelzebub",
    "Steins;Gate Movie: Fuka Ryouiki no Déjà vu",
    "Hajime no Ippo",
    "Jibaku Shounen Hanako-kun",
    "Lovely★Complex",
    "Hunter x Hunter",
    "Karakai Jouzu no Takagi-san",
    "Kenja no Mago",
    "Ajin",
    "Majo no Takkyuubin",
    "Yofukashi no Uta",
    "Mondaiji-tachi ga Isekai kara Kuru Sou desu yo?",
    "Gake no Ue no Ponyo",
    "Gangsta.",
    "Kaifuku Jutsushi no Yarinaoshi",
    "Kiss x Sis (TV)",
    "Boku no Hero Academia the Movie 2: Heroes:Rising",
    "Given",
    "Drifters",
    "Bocchi the Rock!",
    "Kuroshitsuji II",
    "Higashi no Eden",
    "Evangelion Movie 1: Jo",
    "Isekai wa Smartphone to Tomo ni.",
    "Katanagatari",
    "Darwin's Game",
    "SK∞",
    "Katekyou Hitman Reborn!",
    "Gintama'",
    "Absolute Duo",
    "Gate: Jieitai Kanochi nite, Kaku Tatakaeri Part 2",
    "Ore no Kanojo to Osananajimi ga Shuraba Sugiru",
    "Kobayashi-san Chi no Maid Dragon S",
    "Nekomonogatari: Kuro",
    "Gosick",
    "Dorohedoro",
    "God Eater",
    "Musaigen no Phantom World",
    "Paprika",
    "Hajimete no Gal",
    "Mashle",
    "Tsuki ga Kirei",
    "Netoge no Yome wa Onnanoko ja Nai to Omotta?",
    "Evangelion Movie 2: Ha",
    "Natsume Yuujinchou",
    "Bleach: Sennen Kessen-hen",
    "Mushoku Tensei II: Isekai Ittara Honki Dasu",
    "Fruits Basket",
    "Vivy: Fluorite Eye's Song",
    "Shakugan no Shana",
    "Itai no wa Iya nanode Bougyoryoku ni Kyokufuri Shitai to Omoimasu.",
    "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru",
    "Vanitas no Karte",
    "Boku wa Tomodachi ga Sukunai Next",
    "Shokugeki no Souma: Gou no Sara",
    "Suzumiya Haruhi no Yuuutsu (2009)",
    "Kizumonogatari I: Tekketsu-hen",
    "Ichiban Ushiro no Daimaou",
    "Kawaii dake ja Nai Shikimori-san",
    "Summertime Render",
    "Overlord IV",
    "Summer Wars",
    "Black Lagoon: The Second Barrage",
    "Zom 100: Zombie ni Naru made ni Shitai 100 no Koto",
    "Shingeki no Kyojin: Kuinaki Sentaku",
    "Citrus",
    "Sousei no Onmyouji",
    "Aldnoah.Zero",
    "Hinamatsuri (TV)",
    "Fruits Basket 2nd Season",
    "Takt Op. Destiny",
    "High School DxD Hero",
    "Megalo Box",
    "Fairy Tail: Final Series",
    "Death March kara Hajimaru Isekai Kyousoukyoku",
    "Inu x Boku SS",
    "Sora yori mo Tooi Basho",
    "Zero no Tsukaima: Futatsuki no Kishi",
    "Re:Creators",
    "JoJo no Kimyou na Bouken Part 6: Stone Ocean",
    "Yosuga no Sora",
    "86 Part 2",
    "Full Metal Panic!",
    "Aho Girl",
    "Usagi Drop",
    "Rurouni Kenshin: Meiji Kenkaku Romantan",
    "Mayo Chiki!",
    "Ookami to Koushinryou II",
    "Mieruko-chan",
    "Seitokai Yakuindomo",
    "Zombieland Saga",
    "Yuru Camp△",
    "Lycoris Recoil",
    "Gleipnir",
    "Tenkuu no Shiro Laputa",
    "Mairimashita! Iruma-kun",
    "Tokyo Ravens",
    "Maoyuu Maou Yuusha",
    "Kimi ni Todoke 2nd Season",
    "Durarara!!x2 Shou",
    "Chobits",
    "Magi: Sinbad no Bouken (TV)",
    "Komi-san wa, Comyushou desu. 2nd Season",
    "Asobi Asobase",
    "Higurashi no Naku Koro ni Kai",
    "Sora no Otoshimono",
    "Fate/Apocrypha",
    "Owarimonogatari",
    "Fruits Basket: The Final",
    "Uzaki-chan wa Asobitai!",
    "Kyokou Suiri",
    "Hataraku Maou-sama!!",
    "Ishuzoku Reviewers",
    "Ookami Shoujo to Kuro Ouji",
    "Net-juu no Susume",
    "Spy x Family Season 2",
    "Tengoku Daimakyou",
    "Boruto: Naruto the Movie",
    "Shingeki no Kyojin OVA",
    "Blue Period",
    "Tanaka-kun wa Itsumo Kedaruge",
    "Made in Abyss Movie 3: Fukaki Tamashii no Reimei",
    "Kizumonogatari III: Reiketsu-hen",
    "Houseki no Kuni",
    "Chihayafuru",
    "Hibike! Euphonium",
    "Toaru Majutsu no Index II",
    "Ore wo Suki nano wa Omae dake ka yo",
    "Gabriel DropOut",
    "Dagashi Kashi",
    "Dr. Stone: New World",
    "Fate/stay night Movie: Heaven's Feel - I. Presage Flower",
    "Watashi ga Motete Dousunda",
    "Kaze no Stigma",
    "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka Gaiden: Sword Oratoria",
    "Gakkougurashi!",]

  constructor() { }

  getNames(): Observable<string[]> {
    return of(this.animeNames);
  }

  filterNames(value: string): string[]{
    const  filterValue = value.toLowerCase();
    return this.animeNames.filter(name =>
    name.toLowerCase().includes(filterValue))

  }

}

